books = [
"I am barefoot_2_2_ne2x.png",
"Papa's brightly colored jacket_2_2_ne2x.png",
"a Polaroid attachment for my friends camera_2_2_ne2x.png",
"a beautiful natural phenomena_2_2_ne2x.png",
"a bowl with some water_2_2_ne2x.png",
"a bunch of other junk and experiments on my bed_2_2_ne2x.png",
"a command line project on an extremely old computer._2_2_ne2x.png",
"a complex oil diffuser that had multiple compartments_2_2_ne2x.png",
"a giant helicopter drone that had a passenger in it_2_2_ne2x.png",
"a giant iceberg in the Arctic with hundreds of people_2_2_ne2x.png",
"a lizard shaped blood stain on a bed sheet or tarp_2_2_ne2x.png",
"a long line composed of mostly children_2_2_ne2x.png",
"a massive explosion_2_2_ne2x.png",
"a massive stream of stars_2_2_ne2x.png",
"a mini roller coaster_2_2_ne2x.png",
"a packet of instant bread mix_2_2_ne2x.png",
"a race, spiral shaped pill, man with spherical head and hand_2_2_ne2x.png",
"a spicy rub with honey in it that makes it sweet and spicy_2_2_ne2x.png",
"a taco like quesadilla with green frosting on top_2_2_ne2x.png",
"a variety of unfinished ceramic toruses_2_2_ne2x.png",
"a very fancy party in a mansion_2_2_ne2x.png",
"an anatomical diagram of a penis_2_2_ne2x.png",
"an elevator operator and a gun like object._2_2_ne2x.png",
"complex patterns and material finishes_2_2_ne2x.png",
"curved plywood lining the walls of the shop_2_2_ne2x.png",
"exposed wires held together with bread clips_2_2_ne2x.png",
"many vertical streams of clouds in the sky_2_2_ne2x.png",
"mattress, or another sort of soft, rectangular hovercraft_2_2_ne2x.png",
"showers and urinals arranged alternatingly_2_2_ne2x.png",
"strange purple crystals and little creatures_2_2_ne2x.png",
"the entire sky explodes with hues of orange and yellow_2_2_ne2x.png",
"tortillas made of very thin sheets of scrambled eggs_2_2_ne2x.png"
]
labels = [
"I am barefoot.",
"Papa's brightly colored jacket.",
"a Polaroid attachment for my friends camera.",
"a beautiful natural phenomena.",
"a bowl with some water.",
"a bunch of other junk and experiments on my bed.",
"a command line project on an extremely old computer.",
"a complex oil diffuser that had multiple compartments.",
"a giant helicopter drone that had a passenger in it.",
"a giant iceberg in the Arctic with hundreds of people.",
"a lizard shaped blood stain on a bed sheet or tarp.",
"a long line composed of mostly children.",
"a massive explosion.",
"a massive stream of stars.",
"a mini roller coaster.",
"a packet of instant bread mix.",
"a race, spiral shaped pill, man with spherical head and hand.",
"a spicy rub with honey in it that makes it sweet and spicy.",
"a taco like quesadilla with green frosting on top.",
"a variety of unfinished ceramic toruses.",
"a very fancy party in a mansion.",
"an anatomical diagram of a penis.",
"an elevator operator and a gun like object.",
"complex patterns and material finishes.",
"curved plywood lining the walls of the shop.",
"exposed wires held together with bread clips.",
"many vertical streams of clouds in the sky.",
"mattress, or another sort of soft, rectangular hovercraft.",
"showers and urinals arranged alternatingly.",
"strange purple crystals and little creatures.",
"the entire sky explodes with hues of orange and yellow.",
"tortillas made of very thin sheets of scrambled eggs."
]