books = [
    "amorphous.png",
    "fractal.png",
    "iphone.png",
    "ripples.png",
    "electric.png",
    "fused.png",
    "long.png",
    "few_fingers.png",
    "gun.png",
    "many_fingers.png",
]
labels = [["fused.png","I feel an invisible animal nipping at my right hand. I try to move my hand but the animal is more aggressively biting it now. I get out the car and pull my hand up to look at it. I see that my fingers are partially fused together and deformed. I wake up and find that my hand was squeezed tightly between my legs."],
["electric.png","I no longer see the video, just blackness. I relax a little more and try to move again. With some struggle I lift my hands and see electric energy coming from them. I have a false awakening, and reach over to my phone to write my dream down."],
["many_fingers.png","At this point I realize I am dreaming and begin to fly instead. I land on the ledge I had aimed for with my car and stop to look at my hands to confirm I'm dreaming. I have at least ten strange fingers per hand. I wake up and attempt to slip back into the dream."],
["fractal.png","I start to ask her about it and suspect that I'm dreaming. I look at my hand to check but it looks very normal. I look away and look back at it. It instantly becomes a fractalline, tree like shape with my fingers branching off into many thinner fingers."],
["few_fingers.png","I wonder if I'm currently dreaming, look down and see a few extra fingers on my hands. I get so excited that I'm dreaming, but try to calm down and focus on staying in the dream. I am still pretty excited and begin to float up uncontrollably."],
["long.png","On the stairs I realized I was dreaming, and looked down to confirm. I saw my fingers grow long and and deformed. Having confirmed my lucidity I decided I wanted to be naked, and I looked down at the white and tan clothes I was wearing and willed them away."],
["amorphous.png","At one point my body was sort of pulsating. Once when I looked down at my fingers in the dream they were amorphous and constantly changing. I kept trying to exercise control, and the dream sort of fought me. I tried to make a bright window thing dark, and it flickered disobediently."],
["gun.png","It becomes a gunfight between the groups. I use my hands as pretend guns and say 'pow' loudly to let everyone know when I am shooting. It appears that real bullets are coming from my fingers because people are getting injured when I fire my finger guns."],
["ripples.png","I notice my vision has little ripples in it, so I rub my hands together and it solidifies some but not entirely. I walk around to explore the living room."],
["iphone.png","I fall asleep and sort of wake out of my body. I get up, lucid, and explore the kitchen. I decide to see what my phone looks like and I see my hand right through the screen."],
]